# Generated by Django 5.0.13 on 2025-03-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Название позиции')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('contact_info', models.CharField(max_length=255, verbose_name='Контактные данные')),
                ('internship_start', models.DateField(verbose_name='Начало стажировки')),
                ('internship_end', models.DateField(verbose_name='Окончание стажировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_application_signed', models.BooleanField(default=False, verbose_name='Заявление подписано')),
                ('application_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер заявления')),
                ('ID_doc', models.CharField(max_length=20, verbose_name='Номер документа')),
                ('INN', models.IntegerField(verbose_name='ИНН')),
                ('authority', models.CharField(max_length=255, verbose_name='Орган выдачи')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
            ],
            options={
                'verbose_name': 'Стажер',
                'verbose_name_plural': 'Стажеры',
            },
        ),
    ]
