# Generated by Django 5.0.13 on 2025-03-14 08:25

import django.db.models.manager
import internshiphub.registration.mixins
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(internshiphub.registration.mixins.ProxyModelReportMixin, 'registration.intern'),
            managers=[
                ('proxy_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
