# Generated by Django 5.0.13 on 2025-03-13 11:01

import django.db.models.manager
import internshiphub.registration.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(internshiphub.registration.mixins.ProxyModelReportMixin, 'registration.intern'),
            managers=[
                ('proxy_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='intern',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
