# Generated by Django 5.0.13 on 2025-03-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_internproxy_intern_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='INN',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН'),
        ),
    ]
