# Generated by Django 5.0.13 on 2025-03-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keydev_reports', '0001_initial'),
        ('registration', '0003_alter_intern_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='reports',
            field=models.ManyToManyField(related_name='interns', to='keydev_reports.reporttemplate', verbose_name='Шаблоны отчетов'),
        ),
    ]
