# Generated by Django 5.0.13 on 2025-03-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('email', models.EmailField(default=None, max_length=254, null=True, verbose_name='Почта')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН')),
                ('passport', models.CharField(blank=True, max_length=255, null=True, verbose_name='Паспортные данные')),
                ('given_organ', models.CharField(blank=True, max_length=255, null=True, verbose_name='Орган выдачи')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Контактные данные')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('application_date', models.DateField(blank=True, null=True, verbose_name='Дата подачи заявления')),
            ],
            options={
                'verbose_name': 'Стажёр',
                'verbose_name_plural': 'Стажёры',
            },
        ),
    ]
