# Generated by Django 5.0.13 on 2025-03-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отчета')),
                ('related_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель')),
                ('file', models.FileField(max_length=255, upload_to='keydev_reports/report_templates/', verbose_name='Файл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('product', models.CharField(blank=True, max_length=100, null=True, verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
            },
        ),
    ]
